import TestPoster from 'views/MarketPlace/images/TestPoster.jpg';
import DiscoPoster from 'views/MarketPlace/images/DiscoPoster.jpg';

import HamburgerPoster from '../images/HamburgerPoster.jpg';
import MoviePoster from '../images/MoviePoster.jpg';
import SportPoster from '../images/sport.jpg';

export const DATA = [
  {
    key: '0',
    title: 'Test Post',
    postdate: 'February22025',
    image1: SportPoster,
    image2: DiscoPoster,
    image3: MoviePoster,
    alt: 'alt text for poster 1',
    desc: 'Hello \n Come grab this thing \n Your Pal, \n Josh',
    cost: 100,
    condition: 'Like New',
    uploader: 'josh.miller',
    status: 'For Sale',
  },

  {
    Id: 1,
    PostedAt: '2025-06-23T14:11:17.7566667',
    Name: 'testedit',
    Price: 80,
    CategoryId: 1,
    CategoryName: 'Clothing & Accessories',
    Detail: 'testing edit',
    ConditionId: 1,
    ConditionName: 'Like New',
    StatusId: 1,
    StatusName: 'For Sale',
    ImagePaths: [
      SportPoster,
      TestPoster,
      DiscoPoster,
      HamburgerPoster,
      MoviePoster,
      SportPoster,
      TestPoster,
      DiscoPoster,
      HamburgerPoster,
      MoviePoster,
    ],
    PosterUsername: 'Josh.Miller',
  },
  {
    key: '1',
    title: 'Poster 2 Title',
    image1: DiscoPoster,
    image2: SportPoster,
    image3: null,
    alt: 'alt text for poster 2',
    desc: 'this is a short descirption',
    org: 'CATHSTU',
    uploader: 'collin.williams',
    status: 'strike',
  },

  {
    key: '2',
    title: 'Event 3',
    image1: TestPoster,
    image2: null,
    image3: null,
    alt: 'alt text for poster hunter',
    desc: 'this is a short descirption',
    org: 'CEC',
    uploader: 'hunter.simpson',
    status: 'unexpired',
  },
  {
    key: '3',
    title: 'Poster 4 Title',
    image1: HamburgerPoster,
    alt: 'alt text for poster 4',
    desc: 'this is a short descirption',
    org: null,
  },
  {
    key: '4',
    title: 'Poster 5 Title',
    image1: SportPoster,
    alt: 'alt text for poster 5',
    desc: 'this is a short descirption',
    org: null,
  },
  {
    key: '5',
    title: 'Movie Night',
    image1: MoviePoster,
    alt: 'alt text for poster hunter1',
    desc: 'this is a short descirption',
    org: 'I-95 Rocks',
  },
  {
    key: '6',
    title: 'Poster 6 Title',
    image1: TestPoster,
    alt: 'alt text for poster 6',
    desc: 'this is2 a short descirption',
    org: 'I-95 Rocks',
  },
  {
    key: '7',
    title: 'Hamburger',
    image1: HamburgerPoster,
    alt: 'alt text for poster 7',
    desc: 'this is a short descirption',
    org: 'I-95 Rocks',
  },
  {
    key: '8',
    title: 'Poster 6 Title',
    image1: SportPoster,
    alt: 'alt text for poster 6',
    desc: 'this is a short descirption',
    org: null,
  },
  {
    key: '10',
    title: 'Computer Science Disco Night',
    image1: DiscoPoster,
    alt: 'alt text for poster 10',
    desc: 'Come one come all to the Computer Science Disco Night! Join us for a night of fun, dancing, and networking with fellow CS enthusiasts.',
    org: 'COMPS',
  },
  {
    key: '11',
    title: 'Woah, Test',
    image1: SportPoster,
    alt: 'alt text for poster 11',
    desc: "Imagine playing Sports as a Computer Science Major.... Couldn't be me.",
    org: 'COMPS',
  },
  {
    key: '9',
    title: 'Poster 6 Title',
    image1: TestPoster,
    alt: 'alt text for poster 6',
    desc: 'this is a short descirption',
    org: null,
  },
];

export default DATA;
