import { MembershipHistory, MembershipHistorySession } from 'services/user';
import { StudentProfileInfo } from 'services/user';
import { Class } from 'services/peopleSearch';
import { Participation } from 'services/membership';
import { TranscriptItems } from 'services/transcript';

const participation1: Participation = Participation.Member;
const currentYear: number = new Date().getFullYear();
const session1: MembershipHistorySession = {
  MembershipID: 2904,
  SessionCode: currentYear - 1 + '09',
  Participation: participation1,
};
const activity1: MembershipHistory = {
  ActivityCode: 'ISO',
  ActivityDescription: 'International Student Organization',
  ActivityImagePath: '',
  Sessions: [session1],
  LatestDate: currentYear - 1 + '-12-15T00:00:00',
};
const participation2: Participation = Participation.Member;
const session2: MembershipHistorySession = {
  MembershipID: 6547,
  SessionCode: currentYear + '01',
  Participation: participation2,
};
const activity2: MembershipHistory = {
  ActivityCode: '360',
  ActivityDescription: '360.gordon.edu',
  ActivityImagePath: '',
  Sessions: [session2],
  LatestDate: currentYear + '-05-10T00:00:00',
};
export const transcriptItems1: TranscriptItems = {
  honors: [],
  experiences: [],
  service: [],
  activities: [activity1, activity2],
};
export const student1: StudentProfileInfo = {
  fullName: 'First M Last',
  Majors: ['Undecided'],
  Minors: [],
  Advisors: [],
  ID: '12345678',
  Title: '',
  FirstName: 'First',
  MiddleName: '',
  LastName: 'Last',
  Suffix: '',
  MaidenName: '',
  NickName: '',
  OnCampusBuilding: 'WIL',
  OnCampusRoom: '320',
  OnCampusPhone: '',
  OnCampusPrivatePhone: '',
  OnCampusFax: '',
  Mail_Location: '778',
  HomeStreet1: '255 Grapevine Rd',
  HomeStreet2: '',
  HomeCity: 'Wenham',
  HomeState: 'MA',
  HomePostalCode: '',
  HomeCountry: 'US',
  HomePhone: '',
  HomeFax: '',
  KeepPrivate: '',
  Barcode: '12312312312312',
  Email: 'first.last@gordon.edu',
  Gender: 'F',
  AD_Username: 'first.last',
  show_pic: 0,
  preferred_photo: 0,
  Country: 'United States of America',
  BuildingDescription: 'Wilson Hall',
  Facebook: '',
  Twitter: '',
  Instagram: '',
  Handshake: '',
  LinkedIn: '',
  Calendar: '',
  PersonType: 'stu',
  CliftonStrengths: null,
  OnOffCampus: 'On Campus',
  OffCampusStreet1: '',
  OffCampusStreet2: '',
  OffCampusCity: '',
  OffCampusState: '',
  OffCampusPostalCode: '',
  OffCampusCountry: '',
  OffCampusPhone: '',
  OffCampusFax: '',
  Cohort: currentYear.toString(),
  Class: Class['Sophomore'],
  Major: 'U',
  AdvisorIDs: '',
  Married: 'N',
  Commuter: 'N',
  Major2: '',
  grad_student: 'N',
  GradDate: '',
  Major3: '',
  Minor1: '',
  Minor2: '',
  Minor3: '',
  MobilePhone: '123-456-7890',
  IsMobilePhonePrivate: 0,
  Major1Description: 'Undecided',
  Major2Description: '',
  Major3Description: '',
  Minor1Description: '',
  Minor2Description: '',
  Minor3Description: '',
  ChapelRequired: 0,
  ChapelAttended: 0,
};
