import { MembershipHistory, MembershipHistorySession } from 'services/user';
import { StudentProfileInfo } from 'services/user';
import { Class } from 'services/peopleSearch';
import { Participation } from 'services/membership';
import { TranscriptItems } from 'services/transcript';

const currentYear: number = new Date().getFullYear();
const sessionFall: MembershipHistorySession = {
  MembershipID: -1,
  SessionCode: currentYear - 1 + '09',
  Participation: Participation.Member,
};
const activityISO: MembershipHistory = {
  ActivityCode: 'ISO',
  ActivityDescription: 'International Student Organization',
  ActivityImagePath: '',
  Sessions: [sessionFall],
  LatestDate: currentYear - 1 + '-12-15T00:00:00',
};
const sessionSpring: MembershipHistorySession = {
  MembershipID: -1,
  SessionCode: currentYear + '01',
  Participation: Participation.Member,
};
const activity360: MembershipHistory = {
  ActivityCode: '360',
  ActivityDescription: '360.gordon.edu',
  ActivityImagePath: '',
  Sessions: [sessionSpring],
  LatestDate: currentYear + '-05-10T00:00:00',
};
export const exampleTranscriptItems: TranscriptItems = {
  honors: [],
  experiences: [],
  service: [],
  activities: [activityISO, activity360],
};
export const exampleStudentProfile: StudentProfileInfo = {
  fullName: 'Example Student',
  Majors: ['Undecided'],
  Minors: [],
  ID: '12345678',
  Title: '',
  FirstName: 'Example',
  MiddleName: '',
  LastName: 'Student',
  Suffix: '',
  MaidenName: '',
  NickName: '',
  OnCampusBuilding: 'WIL',
  OnCampusRoom: '000',
  OnCampusPhone: '',
  OnCampusPrivatePhone: '',
  OnCampusFax: '',
  Mail_Location: '000',
  HomeStreet1: '255 Grapevine Rd',
  HomeStreet2: '',
  HomeCity: 'Wenham',
  HomeState: 'MA',
  HomePostalCode: '',
  HomeCountry: 'US',
  HomePhone: '',
  HomeFax: '',
  KeepPrivate: '',
  Barcode: '12312312312312',
  Email: 'example.student@gordon.edu',
  Gender: 'F',
  AD_Username: 'example.student',
  show_pic: 0,
  preferred_photo: 0,
  Country: 'United States of America',
  BuildingDescription: 'Wilson Hall',
  Facebook: '',
  Twitter: '',
  Instagram: '',
  Handshake: '',
  LinkedIn: '',
  Calendar: '',
  PersonType: 'stu',
  CliftonStrengths: null,
  OnOffCampus: 'On Campus',
  OffCampusStreet1: '',
  OffCampusStreet2: '',
  OffCampusCity: '',
  OffCampusState: '',
  OffCampusPostalCode: '',
  OffCampusCountry: '',
  OffCampusPhone: '',
  OffCampusFax: '',
  Cohort: currentYear.toString(),
  Class: Class['Sophomore'],
  Major: 'U',
  AdvisorIDs: '',
  Married: 'N',
  Commuter: 'N',
  Major2: '',
  grad_student: 'N',
  GradDate: '',
  Major3: '',
  Minor1: '',
  Minor2: '',
  Minor3: '',
  MobilePhone: '123-456-7890',
  IsMobilePhonePrivate: 0,
  Major1Description: 'Undecided',
  Major2Description: '',
  Major3Description: '',
  Minor1Description: '',
  Minor2Description: '',
  Minor3Description: '',
  ChapelRequired: 0,
  ChapelAttended: 0,
  plannedGradYear: '',
  isPlannedGradYearPrivate: 0,
};
